import sqlmodel
"""rebuild

Revision ID: 9158ee9700c0
Revises: a1b1940d57a0
Create Date: 2024-05-12 11:06:57.140803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9158ee9700c0'
down_revision: Union[str, None] = 'a1b1940d57a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
