import sqlmodel
"""rebuild

Revision ID: aeb51789e032
Revises: 58603872caad
Create Date: 2024-05-12 13:35:35.650523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb51789e032'
down_revision: Union[str, None] = '58603872caad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    op.add_column('city', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'description')
    op.create_table('page',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='page_pkey')
    )
    # ### end Alembic commands ###
